version: 2.1

jobs:
  preview_deployment:
    docker:
      - image: cimg/node:20.16   # or another Node 20+ image
    steps:
      - checkout
      - run:
          name: Pull Vercel Environment Information (preview)
          command: npx vercel@latest pull --yes --environment=preview --token=$VERCEL_TOKEN
      - run:
          name: Build Project Artifacts (preview)
          command: npx vercel@latest build --token=$VERCEL_TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel (preview)
          command: npx vercel@latest deploy --prebuilt --token=$VERCEL_TOKEN

  production_deployment:
    docker:
      - image: cimg/node:20.16
    steps:
      - checkout
      - run:
          name: Pull Vercel Environment Information (production)
          command: npx vercel@latest pull --yes --environment=production --token=$VERCEL_TOKEN
      - run:
          name: Build Project Artifacts (production)
          command: npx vercel@latest build --prod --token=$VERCEL_TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel (production)
          command: npx vercel@latest deploy --prebuilt --prod --token=$VERCEL_TOKEN

workflows:
  version: 2
  preview_and_production:
    jobs:
      - preview_deployment:
          filters:
            branches:
              ignore: main
      - production_deployment:
          filters:
            branches:
              only: main
